Merging the account manager into the plugin
nerc-project/coldfront-plugin-cloud pull request #134
Opened 2024-01-17 21:55 UTC by QuanMPhm

Addressing #114, I am merging the account manager into the plugin. Most changes are in `openshift.py`

2024-01-18 16:43 UTC, knikolla requested changes

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
>      def session(self):
Session is not required anymore since you're not making API calls to the `acct-mgt` service through HTTPS.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/acct_mgt/defaults.py
> +"""Default values for Flask app configuration"""
This file is not required anymore.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/acct_mgt/moc_openshift.py
> +            "msg": f"added user {user_name} to role {role} in {project_name}",
This comment applies to the entire file. Log these messages instead of returning them.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        self.allocation = allocation
Since these are operations performed by the base class, I suggest letting the base class handle them and calling the base class constructor. See https://realpython.com/python-super/

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +                return {"msg": f"user created ({unique_id})"}
These should be logged rather than returned.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +            if self.client.user_exists(username):
A user existing should mean all components of the user. The `user` the `identity` and the `useridentitymapping`.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +from .acct_mgt import moc_openshift
Please use the same syntax for importing the module as the rest of the imports (absolute rather than relative.)

In addition, generally the ordering of imports that I have followed in this repository is
```
python standard library imports
empty line
python imports from library not in standard library
empty line
python imports from the same package as this one (so everything from `coldfront_plugin_cloud`)
```

Please try to follow the same conventions when possible.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +ENVPREFIX = "ACCT_MGT_"
These shouldn't be "ACCT_MGT_" anymore.

2024-01-18 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +def env_config():
It should be possible to load different configurations in a scenario where there are multiple OpenShift Resources.(Ex. see how you can load different credentials based on the Resource name as we did earlier for both OpenStack and OpenShift)

2024-01-19 21:32 UTC, larsks requested changes
I would like to see this series of commits cleaned up:

- Each commit should have a clear purpose and should be clearly described. There should be a short descriptive subject followed by information about why the changes are necessary.
- There should not be multiple commits with the same subject.
- Please check messages for spelling and grammar.
- Typo fixes and other cleanups should be folded into other commits.

2024-01-24 16:28 UTC, QuanMPhm commented
I will likely need to close this PR and open a new one, hopefully with a lot more cleanup and up to standard

2024-01-24 19:43 UTC, larsks commented
> I will likely need to close this PR and open a new one

Please don't do that. Just update this PR.

2024-01-31 13:59 UTC, knikolla commented
Great work on cleaning up the commits. One final advice. You can see that when you merged the main branch back into this working branch, it introduced a series of extraneous commits into your history. It's generally better to rebase your working branch into the main branch. Please look into and remove the merge commits from your history. I suggest you backup your work too, just in case something goes wrong modifying the history.

See this Stackoverflow answer quickly describing the differences between the two workflows https://stackoverflow.com/questions/804115/when-do-you-use-git-rebase-instead-of-git-merge

2024-01-31 18:12 UTC, QuanMPhm commented
@knikolla I've resolved all comments so far. The things I see that are left to do is to rename the OS_AUTH_URL attribute, and update the test files as you see fit. I will wait for further instructions.

2024-02-06 16:54 UTC, larsks commented on src/coldfront_plugin_cloud/openshift.py
> +        openshift_token = os.getenv(f"OPENSHIFT_{var_name}_TOKEN")
Instead of passing in a token, can we just read the configuration from a `kubeconfig` file? Using `config.load_kubeconfig()` will work with both the in-cluster configuration for a serviceaccount and with a local `kubeconfig` file (and respects the `KUBECONFIG` environment variable).

If you don't want to change this now, it may be worth turning into an issue.

2024-02-06 16:54 UTC, larsks commented on src/coldfront_plugin_cloud/openshift.py
> +                return "TODO create user"
Why are we returning a string here (and nowhere else in this function)?

2024-02-06 16:54 UTC, larsks commented on src/coldfront_plugin_cloud/openshift.py
> +            raise Conflict("400: " + f"user already exists ({unique_id})")
Avoid including http response codes in our text messages. We're already providing the response code to the client as part of the HTTP response. Also, we should be returning a 409 status code on conflicts.

2024-02-13 14:08 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openshift.py
> +            raise Conflict("400: " + f"user already exists ({unique_id})")
@larsks @knikolla  Currently I am handling the exceptions the same way that the [current code](https://github.com/nerc-project/coldfront-plugin-cloud/blob/1fff22e096c3440bb783f1152a985f14eeef47b9/src/coldfront_plugin_cloud/openshift.py#L67) is handling it, by passing the response and the message. Should I still remove all error codes?

As for whether the `Conflict` exception returns the appropriate code, that doesn't seem to be implemented yet. `Conflict` is simply subclassed from the built-in `Exception` class. Let me know if I should implement it.

2024-03-05 17:09 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openshift.py
> +            raise Conflict("400: " + f"user already exists ({unique_id})")
From what I've read about Django exception handling, there is no way to raise custom exceptions in Django which returns custom status codes in the http response, especially not in a signal handler, as is the case with `openshift.py`. 
When an error is raised (as in the example you highlighted), Django by default returns `500` as the status code.

The only way I can see to return appropriate errors is by including it in the error message. Please tell me if I missed something and that there is a clean way of returning custom errors.

2024-03-11 13:35 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        openshift_token = os.getenv(f"OPENSHIFT_{var_name}_TOKEN")
For now we can keep passing the token as an environment variable, as that preserves the original behavior. We can work out a better way in the future.

2024-03-11 14:03 UTC, knikolla requested changes
I'll do another pass later today as I ran out of time now.

2024-03-11 14:05 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +            raise Conflict("400: " + f"user already exists ({unique_id})")
We don't need to return custom error codes in Django. These exceptions are purely for the code itself to handle, not any external user.

2024-03-12 01:30 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openshift.py
> +            return
It seems the purpose of `_get_role` and `_get_project` is [purely to check i](https://github.com/nerc-project/coldfront-plugin-cloud/blob/6228541b18ca776124d5096ff8ecca2109df1634/src/coldfront_plugin_cloud/tests/functional/openshift/test_allocation.py#L53)f the role or project has been created on the Openshift cluster. I've actually broke the test cases here by converting the exception raise to a log message.

2024-03-14 18:34 UTC, joachimweyl commented
Blocked on Functional test.

2024-03-26 17:48 UTC, QuanMPhm commented
@knikolla I have brought over the unit tests from the account manager and hopefully resolved all problems with the functional tests

2024-07-26 13:21 UTC, joachimweyl commented on src/coldfront_plugin_cloud/openshift.py
> +            raise Conflict("400: " + f"user already exists ({unique_id})")
@QuanMPhm if you have made this change please resolve this conversation or ask one of those in the conversation to resolve it if you are not sure.

2024-07-26 13:21 UTC, joachimweyl commented on src/coldfront_plugin_cloud/openshift.py
> +            raise Conflict("409: " + f"user already exists ({unique_id})")
@QuanMPhm if you removed the line please resolve this conversation.

2024-07-26 13:23 UTC, joachimweyl commented on src/coldfront_plugin_cloud/openshift.py
> +            return
@knikolla what are your thoughts on this approach?

2024-09-06 13:31 UTC, joachimweyl commented
@QuanMPhm what are the next steps?

2024-09-06 13:32 UTC, joachimweyl commented
@QuanMPhm what are the next steps?

2024-11-05 16:35 UTC, QuanMPhm commented
Now that this PR has been refactored into smaller PRs (#175 #187 #186 #185 #184), I will be closing this now.

2024-11-05 16:35 UTC, closed without merging