Draft PR to intergrate ESI into Coldfront
nerc-project/coldfront-plugin-cloud pull request #146
Opened 2024-03-11 19:31 UTC by QuanMPhm

#135 I've made a small change in openstack.py so that Openstack allocations can be made on clusters with some services missing. This is done by querying the cluster to see which services are available.

As for the complete integration of ESI, there are several things I need to ask before completing the integration, which I have left as comments in the various files, marked with `(Quan Pham) TODO`. So far I have only added a few skeleton files, which I will implement after I know everything I need to know.

2024-03-13 18:54 UTC, tzumainn reviewed
Hi! Just a general comment: ESI doesn't require nova/compute, so that's something you'll want to take out of the ESI quotas (and probably the "small openstack" tests).

2024-03-13 18:55 UTC, tzumainn commented on src/coldfront_plugin_cloud/tests/functional/openstack_mini/test_allocation.py
> +class TestSmallOpenstack(base.TestBase):
Maybe "BareMetalOpenStack"? And include identity/networking/volume?

2024-03-14 20:04 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/tests/functional/openstack_mini/test_allocation.py
> +class TestSmallOpenstack(base.TestBase):
That's not actually the unit test to test the ESI integration. That's just the test to make sure that Coldfront doesn't crashes if we attempt to make **Openstack** allocations on Openstack clusters that might be missing some services, like Cinder and Swift.

This is why in `ci/devstack_mini.sh`, I disabled cinder and swift.

2024-03-18 16:27 UTC, QuanMPhm commented
@tzumainn Do you have an answer for the other questions I mentioned in my PR comments? I feel like there is a lot more information I need to know before being able to remotely continue solving this issue.

2024-03-18 17:28 UTC, tzumainn commented
> @tzumainn Do you have an answer for the other questions I mentioned in my PR comments? I feel like there is a lot more information I need to know before being able to remotely continue solving this issue.

Whoops, sorry, I missed that there were question in the files themselves; in the future it may be easier to add questions as git comments on the PR and tag the relevant people.

Anyway, floating IPs and networks are the only items I can think of that might require allocations, since I think we explicitly do not want ColdFront to limit capacity for leasing nodes.

2024-03-18 18:45 UTC, QuanMPhm commented on README.md
> +(Quan Pham) TODO Add instructions for configuring ESI
Are there any specific instructions for me as I update the README to include information about configuring ESI?

2024-03-18 18:47 UTC, tzumainn commented on README.md
> +(Quan Pham) TODO Add instructions for configuring ESI
Ah, this I wouldn't know; I guess it would be `add_esi_resource`, since this would be distinct from OpenStack? Kristi may know for sure, though.

2024-03-18 18:57 UTC, QuanMPhm commented on ci/devstack_esi.sh
> +# to test ESI
What openstack services do we need for to deploy a Devstack cluster for the purpose of testing the ESI service? Do we want to test the ESI integration against more than one Devstack cluster?

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/attributes.py
> +# From Mainn's suggesting, I've added networks and floating ips
What ESI specific allocation attribute should be included?

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/esi.py
> +# (Quan Pham) TODO Know which resources ESI needs, and their multipliers
What are the multipliers and static additions for the different ESI resources? And what exactly will these resources be?

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/esi.py
> +    # And know which functions needs to be implement specially for ESI
This question can be addressed after we know exactly how Coldfront should interact with an ESI cluster when an ESI allocation is approved/denied: What are all the functions that should be implement for the ESI allocator?

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/add_esi_resource.py
> +            value='Unit of ???' # (Quan Pham) TODO Know what each allocation unit corresponds to
What should be the description text for an ESI allocation unit?

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +        # in tasks.py or utils.py as functions for each resource type?
How exactly should we validate ESI allocations? Since the test Devstack clusters we're running to test ESI integration might not require Ironic or ESI to run on them, how should the allocations be validated without directly testing ESI functionality?

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openstack.py
> +# are available. It is probably a bad idea to hardcode the service names here
This is less a question, and more of a proposal for a future issue. The names of the services listed in the `QUOTA_KEY_MAPPING` dict should match what is in the Openstack Service Type Authority to allow easier tracking of what Openstack objects/services our Coldfront plugin is directly interacting with.

2024-03-18 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/tests/functional/esi/test_allocations.py
> +    # What do we need to test?
How should the test cases for the ESI integration be designed?

2024-03-18 19:00 UTC, tzumainn commented on ci/devstack_esi.sh
> +# to test ESI
It depends what you're testing; ideally Keystone/Neutron/Ironic/Glance. However, if you're only testing quotas, you really only need Keystone/Neutron.

2024-03-18 19:01 UTC, tzumainn commented on src/coldfront_plugin_cloud/attributes.py
> +# From Mainn's suggesting, I've added networks and floating ips
Networks and floating IPs are all I can think of.

2024-03-18 19:01 UTC, tzumainn commented on src/coldfront_plugin_cloud/esi.py
> +# (Quan Pham) TODO Know which resources ESI needs, and their multipliers
I'm not exactly sure what multipliers and static additions mean, so this may be a question for Kristi.

2024-03-18 19:02 UTC, tzumainn commented
I've answered the ESI specific questions; however, I'm not all that familiar with ColdFront itself, so this questions regarding allocations and the like may be better suited for Kristi.

2024-03-19 14:32 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/esi.py
> +# (Quan Pham) TODO Know which resources ESI needs, and their multipliers
Multipliers and static additions refer to what an "Allocation Unit" for an ESI allocation represents. For other resources that can be allocated like [Openstack](https://github.com/nerc-project/coldfront-plugin-cloud/blob/6228541b18ca776124d5096ff8ecca2109df1634/src/coldfront_plugin_cloud/tasks.py#L21), 1 allocation unit represented 1 CPU, 4G RAM, 20G Disk Storage, etc. If the user asked for 3 allocation units of Openstack, they would be asking for a quota of 3 CPU, 12G RAM, and so on. This means each Openstack resource (CPU, RAM, etc) has a "multiplier" (1, 4G, ...) that is used to determine how much of each resource is in one allocation unit. Additionally, each Openstack allocation has a ["static" amount of certain resources ](https://github.com/nerc-project/coldfront-plugin-cloud/blob/6228541b18ca776124d5096ff8ecca2109df1634/src/coldfront_plugin_cloud/tasks.py#L45C6-L45C15)that are always included, which are 2 Floating IPs. These are the "static additions".

This is to say, I don't know what one allocation unit of ESI would represent, and would therefore like to know the multipliers and static additions for each of its resources (floating IPs, networks, etc)

2024-03-19 14:41 UTC, tzumainn commented on src/coldfront_plugin_cloud/esi.py
> +# (Quan Pham) TODO Know which resources ESI needs, and their multipliers
Okay, yeah, that's more of a policy question - I wouldn't be the right person to answer that.

2024-06-28 19:28 UTC, QuanMPhm commented on README.md
> +(Quan Pham) TODO Add instructions for configuring ESI
@knikolla Your thoughts?

2024-06-28 19:31 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/esi.py
> +# (Quan Pham) TODO Know which resources ESI needs, and their multipliers
@knikolla Based on our earlier meeting today, I'm guessing 1 network and 1 floating ip is good?

2024-06-28 19:36 UTC, knikolla commented on src/coldfront_plugin_cloud/esi.py
> +# (Quan Pham) TODO Know which resources ESI needs, and their multipliers
Yes.

2024-06-28 19:38 UTC, knikolla commented on README.md
> +(Quan Pham) TODO Add instructions for configuring ESI
I guess same things that apply for OpenStack in terms of parameters, since the way Keystone is configured is the same. Just make a new command called `add_esi_resource`.

2024-06-28 19:39 UTC, knikolla commented on ci/devstack_esi.sh
> +# to test ESI
@QuanMPhm Don't even do a new Devstack cluster, just reuse the same one that is already installed in the CI and don't worry about Ironic for now.

2024-06-28 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/esi.py
> +    # And know which functions needs to be implement specially for ESI
Just create a new Kyestone project, users, assigns roles, same as OpenStack. Then set quotas, only neutron quotas on networks and floating ips.

2024-06-28 19:41 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/add_esi_resource.py
> +            value='Unit of ???' # (Quan Pham) TODO Know what each allocation unit corresponds to
List the quotas that are specified in the same way that we do for OpenStack. In this case it's only networks and floating ips.

2024-06-28 19:42 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +        # in tasks.py or utils.py as functions for each resource type?
Same as for OpenStack. Is project created and users added correctly. Is quota set correctly.

2024-07-02 20:24 UTC, QuanMPhm commented
@knikolla I have finished the integration code for now. For some unrelated reason the microshift test case is not working. I will update the README once we finish code review.

2024-07-02 21:24 UTC, knikolla requested changes

2024-07-02 21:24 UTC, knikolla commented on src/coldfront_plugin_cloud/esi.py
> +    def set_quota(self, project_id):
I'm assuming you copied this function instead of using the one in the base class because it accesses the `QUOTA_KEY_MAPPING` from the `openstack` module.

If you made `QUOTA_KEY_MAPPING` an attribute of the `OpenStackResourceAllocator` class then you can keep overload it in this subclass and therefore keep this function in the base class without copying it.

2024-07-03 14:50 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/esi.py
> +    def set_quota(self, project_id):
I decided to leave `QUOTA_KEY_MAPPING` outside the class since making it a class attribute would require making small changes in many places that reference the `QUOTA_KEY_MAPPING`. Will that be fine?

2024-07-08 19:26 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openstack.py
> +# are available. It is probably a bad idea to hardcode the service names here
This idea is moot for now since we no longer want to query openstack to see what services are available

2024-07-17 19:50 UTC, knikolla commented on src/coldfront_plugin_cloud/esi.py
> +    def set_quota(self, project_id):
I think those small changes are reasonable, considering they will allow us to avoid repeating the logic in `get_quota` and `set_quota`.

2024-07-26 13:09 UTC, joachimweyl commented on src/coldfront_plugin_cloud/esi.py
> +    def set_quota(self, project_id):
@knikolla is this conversation resolved?

2024-07-26 13:10 UTC, joachimweyl commented
@tzumainn once @knikolla approves the ColdFront side are you ready to approve the ESI side?

2024-09-06 13:46 UTC, tzumainn commented
@joachimweyl sure - given that ESI is just OpenStack, and I don't have much expertise with ColdFront, I would assume everything just kind of works.

2024-09-06 14:41 UTC, joachimweyl commented
@knikolla do you approve the ColdFront side?

2024-09-26 18:23 UTC, knikolla requested changes

2024-09-26 18:23 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/add_esi_resource.py
> +from django.core.management.base import BaseCommand
I'd rather just use the `add_openstack_resource` function with a new flag for mentioning this is ESI.

2024-09-26 18:23 UTC, knikolla commented on src/coldfront_plugin_cloud/attributes.py
> +ESI_FLOATING_IPS = 'ESI Floating IP Quota'
Just use the OpenStack attribute.

2024-09-26 18:23 UTC, knikolla commented on src/coldfront_plugin_cloud/attributes.py
> +ESI_NETWORKS = 'ESI Network Quota'
Keep the attribute name as OpenStack specific rather than mentioning ESI. Don't make it automatically be added to OpenStack projects though.

2024-09-26 18:23 UTC, knikolla commented on src/coldfront_plugin_cloud/esi.py
> +    def get_quota(self, project_id):
In the OpenStack base class create a new method called `get_network_quota` and reuse the same logic in both places.

2024-10-17 19:45 UTC, knikolla requested changes
Almost there!

2024-10-17 19:45 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/add_openstack_resource.py
> +from sre_constants import OP_IGNORE
Is this used and if so, what is this used for?

2024-10-17 19:45 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +        for resource_name in ['OpenStack', 'ESI']:
A more accurate variable name would be `resource_type`, since this corresponds to the type of resource rather than its name.

2024-10-17 19:45 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    name=resource_name
I'm curious if you're able to use something like `name__in` here. The addition of the extra level of indentation required by `for resource in [OpenStack, ESI]` messes up the diff enough to make it hard to parse what has changed.

I think you should try to split out the `for allocation in openstack_allocations` loop from inside this loop by creating an `openstack_allocations` list that has allocations for both ESI and OpenStack.

2024-10-17 19:45 UTC, knikolla commented on README.md
> +(Quan Pham) TODO Add instructions for configuring ESI
This is still unresolved. Please update or remove.

2024-10-18 18:11 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/add_openstack_resource.py
> +from sre_constants import OP_IGNORE
That's a mistake :P

2024-10-23 13:38 UTC, knikolla approved these changes

2024-10-23 13:38 UTC, knikolla commented on README.md
> +(Quan Pham) TODO Add instructions for configuring ESI
This is still unresolved. Please update or remove.

2024-10-24 18:20 UTC, knikolla approved these changes

2024-10-30 19:22 UTC, naved001 commented on src/coldfront_plugin_cloud/openstack.py
> +    QUOTA_KEY_MAPPING_ALL_KEYS = {quota_key: quota_name for k in QUOTA_KEY_MAPPING.values() for quota_key, quota_name in k['keys'].items()}
I don't understand why this change is needed when the original code is much more readable than this.

2024-10-30 19:22 UTC, naved001 commented on src/coldfront_plugin_cloud/tests/functional/esi/test_allocations.py
> +                                                         allocation)
formatting?

2024-10-31 18:57 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openstack.py
> +    QUOTA_KEY_MAPPING_ALL_KEYS = {quota_key: quota_name for k in QUOTA_KEY_MAPPING.values() for quota_key, quota_name in k['keys'].items()}
I wanted to turn `QUOTA_KEY_MAPPING` and `QUOTA_KEY_MAPPING_ALL_KEYS` into class attributes because I wanted the `esi.py` module to be able to override it, which would prevent some redundant code down the line. 

As for the formatting of `QUOTA_KEY_MAPPING_ALL_KEYS`, that's a formatting oversight on my part. I could make initialize it in the allocator's `__init__()` function if you'd like, though I thought that would lead to a messier diff. 

For now, I've reformatted it to look more proper.

2024-11-13 19:39 UTC, joachimweyl commented
@naved001 is this resolved?

2024-11-22 16:47 UTC, naved001 approved these changes

2024-12-13 18:53 UTC, merged