Migrating to using upstream keystone oidc plugin
nerc-project/coldfront-plugin-cloud pull request #150
Opened 2024-03-15 20:32 UTC by QuanMPhm

#149 I edited the devstack functional test to use upstream Keystone's OIDC plugin. A few files from the [old plugin repo](https://github.com/knikolla/devstack-plugin-oidc) were copied and embedded in devstack.sh since I don't know a better place to put them. I am happy to relocate these files given advice.

2024-03-19 18:55 UTC, knikolla requested changes
Looks pretty good! Some minor comments to separate the scripts into own files within the `ci` directory.

2024-03-19 18:55 UTC, knikolla commented on ci/devstack.sh
> +' >> mapping.json
It's fine if this is a separate file rather than being echoed into a file. Call it `devstack_mapping.json`

2024-03-19 18:55 UTC, knikolla commented on ci/devstack.sh
> +" >> test_oidc_login.py
It's fine if this is it's own file rather than being echoed into a file. Call it `devstack_test_oidc_login.py`.

2024-03-19 18:55 UTC, knikolla commented on ci/run_functional_tests_openstack.sh
> +HOST_IP=`ip addr show eth0 | grep "inet " | awk '{ print $2 }' | awk -F "/"  '{ print $1 }'`
This section is repeated in both file, so carve it out into its own file `devstack_config_ip.sh` and use it from there.

2024-03-20 03:38 UTC, QuanMPhm commented
I have moved the files embedded in ci/devstack.sh into their own seperate files, as well as moving the code that sets the HOST_IP variable to its own file.

2024-03-21 14:32 UTC, knikolla approved these changes

2024-03-21 14:32 UTC, knikolla commented on ci/run_functional_tests_openstack.sh
> -source /opt/stack/devstack-plugin-oidc/tools/config.sh
This is fine, but no need to use the `$PWD` variable when you can use relative paths. 

```bash
source ci/devstack-config-ip.sh
```

2024-03-21 14:33 UTC, merged