Added management command to migrate field of sciences
nerc-project/coldfront-plugin-cloud pull request #154
Opened 2024-04-10 18:42 UTC by QuanMPhm

I've moved the PR for field of science migration over here from [`coldfront-plugin-api`](https://github.com/nerc-project/coldfront-plugin-api/pull/38)

2024-04-10 19:40 UTC, knikolla requested changes

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
I think field should be plural here, fields of science.

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    help = """Migrates Coldfront's list of fields of sciences (fos), changing what
If you want to go with FOS, the acronym should be capitalized in the occurrences of this help section or when logged or printed out.

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    Requires a csv, tab-seperated, containing two columns, the first containing the list of old fos,
Why did you choose a tab separated CSV instead of a normal CSV?

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +        return [mapping_dict, new_fos_set]
I find returning two values from a function usually not good for readability and easy of understanding of the code base, but if you really want to return like this, do return a tuple.

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +        return [mapping_dict, new_fos_set]
Honestly, you don't need to return both as the `new_fos` set is the unique list of objects of the dict.

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    def _create_new_fos(new_fos_set):
You can create the new Fields of Science as you iterate over the list in `_migrate_fos`. Change this function to only create one FOS as provided per argument.

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +                is_selectable=True,  # Assuming we want all new fos to be selectable
Remove these 2 comments. The line of code is pretty explanatory of what is being assumed.

2024-04-10 19:40 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +        # Migrate all projects to new fos
This comment is unnecessary as the for loop explains the exact same thing.

2024-04-10 19:42 UTC, knikolla commented
@QuanMPhm I've updated the description of your PR to contain the original description. Please make sure the PR contains all the information here when you submit it rather than require looking somewhere else.

2024-04-11 13:28 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    help = """Migrates Coldfront's list of fields of sciences (fos), changing what
Looking at Coldfront's list of [Fields of Science](https://github.com/ubccr/coldfront/blob/main/coldfront/core/field_of_science/management/commands/data/field_of_science_data.csv), some of the current FOSs contains commas in their description, like "Atomic, Molecular, and Optical Physics"

2024-04-11 13:54 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    Requires a csv, tab-seperated, containing two columns, the first containing the list of old fos,
Looked, and the fields of science CSV in upstream ColdFront also is tab-separated. Works for me to be consistent.

2024-04-11 21:24 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_fields_of_science.py
> +                new_fos = self._get_or_create_new_fos(description=new_fos_name)
I was wrong, you were right to create all fields of science in a separate pass. In this way if an old field of science has not been selected for any project the new one will not be created.

2024-04-11 21:26 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    def _create_new_fos(new_fos_set):
Sorry, I was wrong, see new comment.

2024-04-12 15:13 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/migrate_field_of_science.py
> +    def _create_new_fos(new_fos_set):
Can't believe I reverted my own feature. Sorry, I should have payed more attention.

2024-04-12 16:36 UTC, knikolla approved these changes

2024-04-12 16:36 UTC, merged