Added rounding to Cost and Rate for storage invoice
nerc-project/coldfront-plugin-cloud pull request #161
Opened 2024-05-15 20:27 UTC by QuanMPhm

Cost will now be rounded to 2 decimal points
Rate will be rounded to 6 decimal points, since the Openshift Gb/hr rates at the time of this commit is $0.000009

2024-05-28 20:48 UTC, knikolla approved these changes

2024-05-29 02:53 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +                    Rate=Decimal(rate),
`rate` is already a Decimal. It's parsed as a decimal if you look in add_arguments. You can't cast float to a decimal and expect the value to be what it "looks". So this seems useless to me because I don't think rate here was of type string anyway.

```
>>> Decimal(0.013)
Decimal('0.01299999999999999940325512426397835952229797840118408203125')
>>> Decimal("0.013")
Decimal('0.013')
```

2024-05-29 02:53 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +                    Cost=Decimal(time * rate).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)
You are just casting the *product* to be decimal type which wouldn't be accurate.

```
>>> time = 2
>>> rate = 0.013
>>> Decimal(rate * time)
Decimal('0.0259999999999999988065102485279567190445959568023681640625')
```

What one would want is something like this:
```
>>> time = 2
>>> rate = "0.013" # note that it's string
>>> time * Decimal(rate)
Decimal('0.026')
```

Since we know time is an integer and rate is a Decimal then we could do:
```
>>> time = 2
>>> rate = Decimal("0.013")
>>> (time * rate).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)
Decimal('0.03')
```
because we expect the product of time and rate to be of type decimal. If not, then the result wouldn't have this quantize method and this would correctly raise an error.

2024-05-29 13:57 UTC, knikolla requested changes
Since rate is already a `Decimal` I don't think this changes the representation format and therefore it wouldn't solve issue #157 which is the purpose of this? Have you tested this @QuanMPhm

2024-05-29 14:31 UTC, knikolla commented
Did some quick [googling](https://stackoverflow.com/a/38847691/21281619). The format method with the `f` flag on a `Decimal` seems to give us what we want.  

```python
>>> a
Decimal('9E-9')
>>> str(a)
'9E-9'
>>> format(a, 'f')
'0.000000009'
```

2024-05-30 20:58 UTC, knikolla requested changes
You have fixed the rounding but you haven't fixed the way rate is written to file.

2024-05-31 16:14 UTC, QuanMPhm commented
@knikolla @naved001 Sorry, I'll do some testing and get back to this soon.

2024-05-31 20:32 UTC, QuanMPhm commented
@knikolla @naved001 I reverted the change to rates, so now an `InvoiceRow` is initialized as such:
```
row = InvoiceRow(
        InvoiceMonth=options['invoice_month'],
        Project_Name=allocation.get_attribute(attributes.ALLOCATION_PROJECT_NAME),
        Project_ID=allocation.get_attribute(attributes.ALLOCATION_PROJECT_ID),
        PI=allocation.project.pi.email,
        Institution_Specific_Code=allocation.get_attribute(
            attributes.ALLOCATION_INSTITUTION_SPECIFIC_CODE
        ) or "N/A",
        Invoice_Type_Hours=time,
        Invoice_Type=su_name,
        Rate=rate,    # Not casting to Decimal
        Cost=(time * rate).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)
)
```
 When I run the script with this command:
`coldfront calculate_storage_gb_hours --openstack-gb-rate 0.000009 --openshift-gb-rate 0.000009`

My output invoice seems to be the desired output?
```
Invoice Month,Project - Allocation,Project - Allocation ID,Manager (PI),Invoice Email,Invoice Address,Institution,Institution - Specific Code,SU Hours (GBhr or SUhr),SU Type,Rate,Cost
2024-05,,,cgray@example.com,,,,N/A,1234,OpenStack Storage,0.000009,0.01
```

2024-05-31 20:53 UTC, knikolla commented
> @knikolla @naved001 I reverted the change to rates, so now an `InvoiceRow` is initialized as such:
> 
> ```
> row = InvoiceRow(
>         InvoiceMonth=options['invoice_month'],
>         Project_Name=allocation.get_attribute(attributes.ALLOCATION_PROJECT_NAME),
>         Project_ID=allocation.get_attribute(attributes.ALLOCATION_PROJECT_ID),
>         PI=allocation.project.pi.email,
>         Institution_Specific_Code=allocation.get_attribute(
>             attributes.ALLOCATION_INSTITUTION_SPECIFIC_CODE
>         ) or "N/A",
>         Invoice_Type_Hours=time,
>         Invoice_Type=su_name,
>         Rate=rate,    # Not casting to Decimal
>         Cost=(time * rate).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)
> )
> ```
> 
> When I run the script with this command: `coldfront calculate_storage_gb_hours --openstack-gb-rate 0.000009 --openshift-gb-rate 0.000009`
> 
> My output invoice seems to be the desired output?
> 
> ```
> Invoice Month,Project - Allocation,Project - Allocation ID,Manager (PI),Invoice Email,Invoice Address,Institution,Institution - Specific Code,SU Hours (GBhr or SUhr),SU Type,Rate,Cost
> 2024-05,,,cgray@example.com,,,,N/A,1234,OpenStack Storage,0.000009,0.01
> ```

I see, then perhaps the bug is with how `process_csv_report` writes down the Rate when it writes the invoices.

If you go to `Invoices/2024-04/` and look at any of the invoices there produced by `process_csv_report` the rate for Storage is written as `9.00E-06`

2024-05-31 20:56 UTC, knikolla commented
@QuanMPhm It seems to be that the issue is now with how it is written in this file but in `process_csv_repoirt`.

 `Rate` in `process_csv_report` is read as a `float` and therefore when it's to file it is persisted like that.

```python
>>> a = "0.000009"
>>> float(a)
9e-06
>>> Decimal(a)
Decimal('0.000009')
```

2024-05-31 20:58 UTC, knikolla approved these changes

2024-05-31 20:58 UTC, merged