Support excluding time intervals during storage invoicing and fixed typo
nerc-project/coldfront-plugin-cloud pull request #174
Opened 2024-08-05 15:42 UTC by QuanMPhm

Closes #166. Added an optional CLI argument which allows passing in a txt file containing excluded time intervals. Each line in the txt file should contain a date range that we want to exclude from billing, formatted as
 "%Y-%m-%d,%Y-%m-%d". An example line could be "2023-02-01,2023-02-03".

The time period excluded from billing starts from the first second of the start date, and ends on the last second of the end date. This means it is possible for the excluded date range to start and end on the same day.

Also fixed a minor typo.

2024-08-05 16:22 UTC, knikolla requested changes
Wouldn't a simpler implementation be to calculate the several billable periods and then call `calculate_quota_unit_hours` multiple times adding up the result?

2024-08-05 16:22 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +                            help='File containing list of date ranges excluded from billing')
Can you please make this accept the arguments directly from the command line rather than a file?

2024-08-05 16:22 UTC, knikolla commented on src/coldfront_plugin_cloud/utils.py
> +def load_exlcluded_intervals(excluded_interval_filepath):
typo in excluded

2024-08-05 16:30 UTC, knikolla commented
> Wouldn't a simpler implementation be to calculate the several billable periods and then call `calculate_quota_unit_hours` multiple times adding up the result?

Nevermind the above comment. I wrote it and then forgot to delete it.

2024-08-05 16:43 UTC, knikolla commented on src/coldfront_plugin_cloud/utils.py
> +def get_included_duration(start: datetime.datetime,
I think I have a better and simpler idea on how to write this function. Will let you know later today when I have more time.

2024-08-05 18:37 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +                            help='File containing list of date ranges excluded from billing')
You want the user to pass in a variable amount of excluded date ranges?

2024-08-05 18:56 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +                            help='File containing list of date ranges excluded from billing')
yes

2024-08-20 18:41 UTC, knikolla requested changes
Two minor style comments that can be quickly resolved but otherwise looks good! Thanks!

2024-08-20 18:41 UTC, knikolla commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +        parser.add_argument('--excluded-date-ranges', type=str,
I believe the way to provide multiple entries by repeating the argument right? `--excluded-date-ranges 2023-04-01,2023-04-02 --excluded-date-ranges 2023-05-01,2023-04-02`.

In that this should be singular `--exluded-date-range`

2024-08-20 18:41 UTC, knikolla commented on src/coldfront_plugin_cloud/tests/unit/test_calculate_quota_unit_hours.py
> +        SECONDS_IN_DAY = 3600 * 24
According to [PEP8](https://www.python.org/dev/peps/pep-0008/#constants) constants should be defined at the module level.

2024-08-21 15:45 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py
> +        parser.add_argument('--excluded-date-ranges', type=str,
I just tested and the way to pass it is by a space-seperated list of arguments. From the [argparse](https://docs.python.org/3/library/argparse.html#nargs) documentation:
```
parser = argparse.ArgumentParser()

parser.add_argument('--foo', nargs='*')

parser.add_argument('--bar', nargs='*')

parser.add_argument('baz', nargs='*')

parser.parse_args('a b --foo x y --bar 1 2'.split())
Namespace(bar=['1', '2'], baz=['a', 'b'], foo=['x', 'y'])
```

2024-08-22 12:47 UTC, knikolla requested changes

2024-08-22 12:47 UTC, knikolla commented on src/coldfront_plugin_cloud/utils.py
> +                    hour=23, minute=59, second=59)
Apologies, I should have caught this in earlier iterations but it only really hit me yesterday evening.

This is inconsistent with how we are treating dates in the rest of this script.

Running the application with `--start 2024-01-01` and `--end 2024-01-02` will produce a 24 interval (from midnight to midnight), however an `--excluded-date-ranges 2024-01-01,2024-01-02` would be a 48 hour interval. 

Regardless of which is the better way, please treat dates as meaning 00:00 on that date to be consistent.

2024-08-22 17:25 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/utils.py
> +                    hour=23, minute=59, second=59)
I see. Sorry for not realizing this design choice as well when implementing the feature.

2024-08-23 18:04 UTC, knikolla approved these changes

2024-08-30 20:13 UTC, naved001 approved these changes
looks good, just couple of optional suggestions.

2024-08-30 20:13 UTC, naved001 commented on src/coldfront_plugin_cloud/utils.py
> +    return math.ceil(total_interval_duration)
@knikolla it's possible that `total_interval_duration` could become negative if the user inadvertently supplies multiple overlapping intervals to exclude. That's obviously user error but it'd still be nice to add an assertion that `total_interval_duartion >=0`

2024-08-30 20:13 UTC, naved001 commented on src/coldfront_plugin_cloud/utils.py
> +        start, end = interval.strip().split(",")
@knikolla do we want to add any assertions that end time is after the start time just in case the user makes a mistake entering these values?

2024-09-06 13:06 UTC, joachimweyl commented
@QuanMPhm have you had a chance to review Naved's suggestions?

2024-09-06 18:17 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/utils.py
> +    return math.ceil(total_interval_duration)
@naved001 I have solved a medium Leetcode problem and added a function that will merge overlapping excluded time intervals

2024-09-06 18:18 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/utils.py
> +        start, end = interval.strip().split(",")
@naved001 I have added an assertion to `load_excluded_intervals`. A corresponding test case has also been added.

2024-09-06 18:20 UTC, QuanMPhm commented
@naved001 @knikolla I've added some small logic additions to the PR, so I will wait for everyone's approval again.

2024-09-06 19:31 UTC, knikolla requested changes

2024-09-06 19:31 UTC, knikolla commented on src/coldfront_plugin_cloud/utils.py
> +def _merge_date_ranges(intervals_list: list):
I appreciate your enthusiasm in writing code to support this, but this then means that accepting overlapping intervals as an argument is a supported feature of the codebase, which we don't want to be the case.

Some explanations as to why:
- The admin running the command will not be incentivized to fix the way they are storing these intervals.
- It may also be the case that some other tools we're using do not implement these merging function, therefore using the same interval on OpenStack billing for example will return an error, but not here. 
- This is a complex function that we'd have to keep supporting moving forward in cases of bugs. 

Please simply check for overlapping intervals or unordered start and end and error in case of malformed input.

2024-09-13 16:43 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/utils.py
> +def _merge_date_ranges(intervals_list: list):
@knikolla Sorry for taking a while to ask this: Since removing support for merging intervals means overlapping intervals will result in faulty billing, I should throw an error for overlapping intervals as well?

2024-10-02 13:50 UTC, knikolla approved these changes

2024-10-02 13:50 UTC, knikolla commented on src/coldfront_plugin_cloud/utils.py
> +    excluded_intervals_list.sort(key=interval_sort_key)
nitpick: You can write this as a lambda.

2024-10-02 13:58 UTC, merged