Allow direct communication to Openshift API through `get_federated_user`
nerc-project/coldfront-plugin-cloud pull request #177
Opened 2024-10-30 17:40 UTC by QuanMPhm

Closes #175. As the first step towards merging the account manager into our coldfront cloud plugin, the `get_federated_user` function in the Openshift allocator will now (through several functions) directly call the Openshift API. Much of the functions added are copied from the `moc_openshift` module in the account manager.

Aside from copying some functions,
implementation of this feature also involved:
- A new resource attribute `Identity Name` for the Openshift idp
- A new unit test for the `get_federated_user` function
- Changes to the CI file to enable these new unit tests

2024-10-31 19:14 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        return kubernetes.dynamic.DynamicClient(k8s_client)
the moc openshift repo was using the openshift dynamic client, is there a reason why you switched to kubernetes dynamic client?

2024-10-31 19:14 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        self.logger.info("404: " + f"user ({username}) does not exist")
just use fstring for the whole string.

2024-10-31 22:03 UTC, larsks commented on src/coldfront_plugin_cloud/tests/unit/openshift/test_user.py
> +        self.mock_openshift_allocator = OpenShiftResourceAllocator(mock_resource, mock_allocation)
I think the naming here may be misleading; this isn't a `mock_openshift_allocator`; this is the real allocator that we are testing.

2024-11-04 19:00 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openshift.py
> +        return kubernetes.dynamic.DynamicClient(k8s_client)
I made a mistake. I didn't notice that the account manager repo was using the openshift dynamic client

2024-11-04 19:06 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openshift.py
> +        self.functional_tests = os.environ.get("FUNCTIONAL_TESTS", "").lower()
As far as I know from looking at git blame, this design choice was made a long time ago and is present is both the openshift and openstack allocators. I open could a new issue for this unless there were strong reasons why this design choice was made. @knikolla Do you have any thoughts?

2024-11-04 20:01 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        self.functional_tests = os.environ.get("FUNCTIONAL_TESTS", "").lower()
In hindsight, I should have called that environment variable something like `INSECURE_HTTPS` because that's the only thing it allows AFAIK. 

@larsks do you want the env variable to be renamed to the above now or in a follow up patch? (there are other occurrences already present in the codebase in the other drivers)

2024-11-12 18:30 UTC, larsks commented on src/coldfront_plugin_cloud/openshift.py
> +        self.functional_tests = os.environ.get("FUNCTIONAL_TESTS", "").lower()
@knikolla A followup patch would be fine.

2024-11-14 15:01 UTC, knikolla requested changes
Overall looks pretty good, some comments.

2024-11-14 15:01 UTC, knikolla commented on src/coldfront_plugin_cloud/tests/unit/openshift/test_user.py
This file is not actually being picked up by the test runner and the tests are not being executed. Python requires a `__init__.py` file to consider directories as Python modules and it's missing here.

2025-02-07 14:59 UTC, QuanMPhm commented on src/coldfront_plugin_cloud/openshift.py
> +        self.functional_tests = os.environ.get("FUNCTIONAL_TESTS", "").lower()
The https check when making the openshift client will now only depend on `OPENSHIFT_{self.safe_resource_name}_VERIFY`. This lead to a small change in the CI file

2025-02-07 15:04 UTC, QuanMPhm commented
I have implemented all feedback so far. The devstack test broke because devstack release 2023.1 is no longer available. I assume this will be fixed with @knikolla 's upcoming [PR](https://github.com/nerc-project/coldfront-plugin-cloud/pull/192)

2025-02-10 14:01 UTC, QuanMPhm commented
@joachimweyl Yep, now the tests are passing

2025-02-10 17:41 UTC, knikolla commented
I'll review this week, though don't want to rush this in for tomorrow's maintenance window.

2025-02-25 18:49 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        self.functional_tests = os.environ.get("FUNCTIONAL_TESTS", "").lower()
@larsks are you concerns with this resolved? can you do another pass at reviewing the PR?

2025-02-26 15:04 UTC, knikolla approved these changes
Looks good to me.

Would like @larsks or @naved001 to do a review too.

After this one merges, can you please do quota operations, and then project operations?

Quota is higher priority than the users because currently that is the only one that requires changes to `acct-mgt` everytime we add a new quota type.

2025-03-03 19:27 UTC, joachimweyl commented on src/coldfront_plugin_cloud/attributes.py
> +RESOURCE_IDENTITY_NAME = 'Identity Name'
I see this is outdated, can this be resolved?

2025-03-18 19:47 UTC, naved001 approved these changes

2025-03-19 14:45 UTC, QuanMPhm commented
Merge waiting on @larsks to resolve his [comment](https://github.com/nerc-project/coldfront-plugin-cloud/pull/177#discussion_r1825061755).

2025-03-25 13:36 UTC, merged