Update docs for OpenShift
nerc-project/coldfront-plugin-cloud pull request #72
Opened 2022-11-18 15:43 UTC by knikolla

2022-12-08 15:42 UTC, jtriley requested changes

2022-12-08 15:42 UTC, jtriley commented on README.md
> +Each OpenStack resource must have the following attributes set in coldfront:
s/OpenStack/OpenShift here and the next line

2022-12-20 16:32 UTC, knikolla commented on README.md
> +Each OpenStack resource must have the following attributes set in coldfront:
Updated to say OpenShift instead of OpenStack. For the next line, the code to change the names of the attributes to remove the prefix has not merged yes, to the attribute actually still has OpenStack in the name. #65

2022-12-20 18:20 UTC, naved001 commented on README.md
> +| Limit on RAM (GB)                     | 2                   |
As far as I know, coldfront sets RAM in MiB for OpenShift.

2022-12-20 18:45 UTC, knikolla commented on README.md
> +| Limit on RAM (GB)                     | 2                   |
You are correct. Will update.

2022-12-20 19:04 UTC, naved001 approved these changes

2022-12-20 19:24 UTC, jtriley approved these changes

2022-12-20 19:24 UTC, merged