Extend validation command to validate openshift quotas
nerc-project/coldfront-plugin-cloud pull request #76
Opened 2022-12-12 15:14 UTC by naved001

this does the thing, but could look nicer and maybe use some refactoring. Looking for feedback.

2022-12-14 15:10 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +            logger.debug(msg)
I don't think I would bother with a throwaway variable here; just write:

```
logger.debug(f"...the message...")
```

2022-12-14 15:10 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                            result = re.search(PATTERN, str(current_value))
Also, since you're making the same `re.search` call in both this case and the following one, why not move `result = re.search(PATTERN, str(current_value))` line out of the `if` statement?

2022-12-14 15:10 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    current_value = quota.get(key, None)
What data type is returned here? You're treating `current_value` as a string value when matching it against a regular expression, but later on you're setting it to an `int` value.

2022-12-14 15:10 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    if expected_value is None and current_value:
Can `current_value` ever legitimately be `0`?

2022-12-14 15:10 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        logger.warning(msg)
Why don't we check for `options["apply"]` in this case (and reset the quota if necessary)?

2022-12-14 15:10 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        if options["apply"]:
It looks like you've applied some reformatting here. It would be helpful if you either (a) omitted these changes, or (b) moved them into a separate commit (because it makes it hard to tell what changes here are operationally significant).

2022-12-14 15:20 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    if expected_value is None and current_value:
good point, I'll try setting it and see what happens!

2022-12-14 15:22 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    current_value = quota.get(key, None)
`current_value` here is a string for all attributes e.g. it could be `"1000Mi"` for RAM, `"20Gi"` for Storage, or `"4"` for CPU. 

So for RAM and Storage quota, I use the regular expression to extract the value and unit, and ultimately get an `int` value of the right unit. I need all to be numbers because that's how coldfront stores these.

2022-12-14 15:23 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        if options["apply"]:
oops, I'll fix this. Been trying out Visual Studio code with  Black formatting enabled, and I guess it formatted stuff when I saved :(

2022-12-14 15:27 UTC, naved001 commented
Thank you for the review @larsks!

2022-12-14 15:52 UTC, larsks commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        if options["apply"]:
I think it makes sense to rigorously format everything with Black (and make that part of the CI checks). Just keep the formatting changes in separate commits.

2022-12-14 18:07 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        if options["apply"]:
okay, I took care of that.

2022-12-14 21:18 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        logger.warning(msg)
We set a boolean `failed_validation`in this block  to `True` and then in a following if statement checks for that boolean and `options["apply"]` to rest the quota. But I think we can just stick the check right here and get rid of setting the unnecessary boolean since that's not used elsewhere.

2022-12-14 21:42 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                            result = re.search(PATTERN, str(current_value))
> What if re.search() fails to find a match?

Then the next call to `result.groups()[0]` will trigger an AttributeError
```
AttributeError: 'NoneType' object has no attribute 'groups'
```
which is then re-raised as a CommandError.

2022-12-14 21:55 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    if expected_value is None and current_value:
OpenShift did let me set the quota value to 0. So`current_value` before this block can be 0 (instead of None), specifically a string `"0"`.

For RAM and Storage, an AttributeError earlier will stop the execution. For CPU, it'll get cast to an `int` and `bool(int("0"))` will return False and it won't go into this block at all.

So I guess I need to handle the case of values being 0 better. Also, `m` is a valid unit for memory apparently which I am not handling

2022-12-19 19:35 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                        logger.warning(msg)
I have now updated this to do the check and reset the quota if necessary.

2022-12-19 19:39 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                    if expected_value is None and current_value:
if `current_value` is `"0"` and `expected_value` is `None`, then we will end up setting the quota to "0" in coldfront, since we don't really know what the actual value should be anyway. It'll at least make it match.

2022-12-19 19:40 UTC, naved001 commented on src/coldfront_plugin_cloud/management/commands/validate_allocations.py
> +                            result = re.search(PATTERN, str(current_value))
I have since updated the code and I am raising a CommandError when re.search() fails to find a match.

2022-12-21 20:33 UTC, larsks approved these changes

2023-01-03 20:49 UTC, knikolla requested changes
Good work! The change looks good to me, but I have a few comments.

First, I want to see it tested before merging. Example of how this is done with OpenStack is here https://github.com/nerc-project/coldfront-plugin-cloud/blob/b5dc67c5e235577667cdf9966b8663e0cf989978/src/coldfront_plugin_cloud/tests/functional/openstack/test_allocation.py#L186-L198

Second, this project doesn't use `black` yet, and I'm not happy with the automatic introduction of unnecessary code restructuring in parts of the file not touched by the scope of this PR.

2023-01-05 15:23 UTC, naved001 commented
@knikolla I removed the formatting changes and added a test similar to that of openstack. Let me know if you want more comprehensive tests.

2023-01-05 15:49 UTC, knikolla commented
Thanks! I'll re-review this evening.

2023-01-06 15:36 UTC, knikolla approved these changes
Looks good to me. Thanks @naved001!

2023-01-06 16:02 UTC, merged