Add support for setting storage and pvc quotas
nerc-project/coldfront-plugin-cloud pull request #80
Opened 2023-01-26 15:52 UTC by knikolla

Adds support for
- requests.storage
- persistentvolumeclaims

Sets the defaults to 10Gi storage and 2 volumes.

Closes #78

2023-01-26 19:11 UTC, naved001 approved these changes

2023-03-24 19:45 UTC, larsks requested changes

2023-03-25 18:25 UTC, larsks commented
Also! If we update to the most recent `openshift-acct-mgt` repository, we get much more useful error messages in the CI tests:

```
coldfront_plugin_cloud.openshift.ApiException: 400:
{"msg":"Unexpected response from OpenShift API:
ResourceQuota
\"81904392343f4596ac0ae8fd1384da56-f2e4b99-project\"
is invalid: [spec.hard[limits.storage]: Invalid
value: \"limits.storage\": must be a standard
resource type or fully qualified,
spec.hard[limits.storage]: Invalid value:
\"limits.storage\": must be a standard resource for
quota]"}
```

2023-03-29 12:08 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +    attributes.QUOTA_LIMITS_STORAGE: lambda x: {":limits.storage": f"{x}Gi"},
Thanks Lars. Updated. I didn't look at the OpenShift documentation and I saw `limits.storage` mentioned [here](https://github.com/CCI-MOC/openshift-acct-mgt/blob/0a7280882f85296d7ddc980a02ab14d5fa6efb41/k8s/base/quotas.json#L7), which was misguiding.

2023-04-10 20:04 UTC, larsks approved these changes

2023-04-10 20:05 UTC, merged