Include Coldfront project name when generating project display name
nerc-project/coldfront-plugin-cloud pull request #88
Opened 2023-02-16 19:58 UTC by naved001

This commit moves `get_unique_project_name` to `utils.py` and then use that when generating the name. It also adds a check to the method to validate the project name.

2023-02-22 15:53 UTC, knikolla requested changes
This isn't going to work because we don't have control over what is inputted as a Project Name in ColdFront. They can include whitespace, and special characters.

For example here is an actual project name that I picked from the current ColdFront system. `TEST - Software & Application Innovation Lab (SAIL) - TEST Projects`

```
>>> get_unique_project_name("TEST - Software & Application Innovation Lab (SAIL) - TEST Projects")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in get_unique_project_name
AssertionError: not a valid project name
```

Also OpenStack doesn't have those limitations (except length), therefore it is desirable to keep the complexity of the name if possible. So it should preserve the current behavior for OpenStack project names. 

You need to provide a method to convert the arbitrary project name provided as an example above to a namespace name that is valid for OpenShift, and use that for the project ID and project Name for OpenShift only.

2023-02-23 15:52 UTC, naved001 commented
@knikolla I have updated this PR.

```
>>> get_sanitized_project_name("TEST - Software & Application Innovation Lab (SAIL) - TEST Projects")
'test---software---application-innovation-lab--sail----test-projects'
```
Note that this is longer than 64 characters, the other method takes care of the length and makes it unique.

> and use that for the project ID and project Name for OpenShift only.

The project display-name does not have to conform to a spec, only the actual name (project_id).  But I am using the sanitized name for display-name anyway. 

```
naved@computer ~ % oc get ns delete-me-because-this-is-a-test -o yaml |oc neat
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Display N@me has bunch of test characters and may be
      a bit too long, does this have a character limitation, we'll see soon
```

2023-02-24 15:27 UTC, knikolla commented
> @knikolla I have updated this PR.
> 
> ```
> >>> get_sanitized_project_name("TEST - Software & Application Innovation Lab (SAIL) - TEST Projects")
> 'test---software---application-innovation-lab--sail----test-projects'
> ```
> 

That looks almost as good as we're ever going to get. Though it might make sense to strip consecutive dashes to save on characters.

2023-02-24 15:27 UTC, knikolla commented on src/coldfront_plugin_cloud/utils.py
> +    # convert to lowercase
This comment is redundant since the following line provides the same exact information. 

Suggestion: It would be more helpful here to provide the motivation and limitations that this method is trying to work around, rather than comment individual lines (except regex, always comment regex.)

For example:

> Returns a sanitized project name that only contains lowercase alphanumeric characters and dashes (not leading or trailing.)

2023-02-24 18:44 UTC, naved001 commented on src/coldfront_plugin_cloud/utils.py
> +    # convert to lowercase
makes sense, I have updated it.

2023-02-24 18:46 UTC, naved001 commented
> Though it might make sense to strip consecutive dashes to save on characters.

@knikolla good point, updated to do that.

```
>>> get_sanitized_project_name("TEST - Software & Application Innovation Lab (SAIL) - TEST Projects")
'test-software-application-innovation-lab-sail-test-projects'
```

2023-02-27 13:15 UTC, joachimweyl commented on src/coldfront_plugin_cloud/utils.py
> +    # convert to lowercase
@knikolla is this resolved?

2023-02-27 15:07 UTC, knikolla requested changes

2023-02-27 15:07 UTC, knikolla commented on src/coldfront_plugin_cloud/tasks.py
> +            project_name = utils.get_unique_project_name(
There's a few things wrong here.

You're calling `get_unique_project_name`, which is trimming it down and adding a random hex at the end, however when you call `create_project` it calls the above method again. Therefore you're ending up with double the random hex at the end for project id, and the display name will not match the project id.

Also, the project name defined here is going to be added to the attribute `Allocated Project Name` and that is going to be different from the name that was assigned as the display name, with the latter being sanitized and this one not.

2023-02-28 14:23 UTC, knikolla requested changes

2023-02-28 14:23 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
You still need to provide a max length here. The base class provides a `project_name_max_length` which we can set in the OpenShift allocator and pass here.

2023-02-28 14:52 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
oops, thanks for pointing that out! Fixed it,

2023-02-28 14:53 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
actually wait, let me do it the right way

2023-02-28 14:58 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
done.

2023-02-28 15:09 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
It looks okay now after the revision, but I'd use the same output from `get_unique_project_name` here for both `project_name` and `project_id`, it will not contain the randomness at the end and it makes sense for consistency.

2023-02-28 15:10 UTC, knikolla commented
Made a last minor comment in the thread, outside of that looks great! Thanks!

2023-02-28 15:15 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
> it will not contain the randomness at the end

You mean it will contain the randomness for project_name?

2023-02-28 16:35 UTC, knikolla commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
Ah, I poorly phrased it. Yes. I meant that in the current state `project_name` does not contain the randomness and is different from the namespace name.

So, just set project_name and the display name to whatever we got for project_id and return that.

2023-02-28 17:07 UTC, naved001 commented on src/coldfront_plugin_cloud/openstack.py
> +    def create_project(self, suggested_project_name) -> base.ResourceAllocator.Project:
@knikolla question: In a method in a derived class, does one really need to indicate the return type? Doesn't having that in the base class sufficient?

We also only did this for openstack ,and not for openshift. So I only updated this here.

2023-02-28 17:08 UTC, naved001 commented on src/coldfront_plugin_cloud/openshift.py
> +        project_id = utils.get_unique_project_name(project_name)
thanks, I have made the change.

2023-02-28 19:04 UTC, knikolla commented on src/coldfront_plugin_cloud/openstack.py
> +    def create_project(self, suggested_project_name) -> base.ResourceAllocator.Project:
Great question. Player around with it.

```python
import abc


class BaseClass(abc.ABC):
    @abc.abstractmethod
    def method(self) -> int:
        pass


class SubClass(BaseClass):
    def method(self):
        return 1

>>> typing.get_type_hints(SubClass.method)
{}
>>> typing.get_type_hints(BaseClass.method)
{'return': <class 'int'>}
```

So, for code that treats instances of `SubClass` as `BaseClass` the type hints are going to work, but for code that instantiates the subclass directly, they aren't.

2023-02-28 19:05 UTC, knikolla approved these changes

2023-02-28 19:23 UTC, merged