Make it easier to run CI locally
nerc-project/coldfront-plugin-cloud pull request #92
Opened 2023-03-27 21:50 UTC by larsks

This is a series of changes to make it easier to run the CI tests in a local Linux environment. In particular:

- We move more configuration into environment variables
- We move distribution-specific package installs to a separate script
- We avoid conflicts with host services running on the same ports used by Microshift and the image registry
- We make it possible to run the tests without clobbering a local `~/.kube/config` file

2023-03-28 01:15 UTC, naved001 approved these changes

2023-03-28 01:15 UTC, naved001 commented on ci/setup-ubuntu.sh
> +sudo apt-get install docker-compose python3-virtualenv
why does this command run in the CI without the `-y` flag?

Another thing I noticed is that the package `docker-compose` recommends `docker.io` so apt will install it if it's missing on the system unless one specifies the `-no-install-recommends` flag (I am not saying we should use that flag, just thought it was interesting).

2023-03-28 13:11 UTC, larsks commented on ci/setup-ubuntu.sh
> +sudo apt-get install docker-compose python3-virtualenv
It should have the `-y` flag.

Good spotting re: `docker-compose`. Since we're not using it, we should just remove it; previously, the `microshift.sh` script was explicitly installing `docker.io`, but GitHub runners already include Docker. I hadn't noticed the dependency.

2023-03-29 12:25 UTC, knikolla requested changes

2023-03-29 12:25 UTC, knikolla commented on ci/microshift.sh
> +mkdir -p ~/.kube
You should use the environment variable `KUBECONFIG` here to figure out where to create the directory.

2023-03-29 12:25 UTC, knikolla commented on ci/microshift.sh
> +git config --global advice.detachedHead false
Since this PR seems to provide some guaranteed regarding being run locally on the developer's environment, I don't feel comfortable changing their global git config.

2023-03-31 21:11 UTC, knikolla approved these changes

2023-03-31 21:11 UTC, merged